name: Review Branch

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  register:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: dev
          imagePackage: app
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register]
    steps:
      - name: Use kube-workflow deployment
        uses: SocialGouv/kube-workflow@v1
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
